### ISSUE TITLE
Exercise 1: Notebook list

### ISSUE THREAD

**Issue by oyamad** [OyamaZemi/exercises2016#1]
コードが書けたら，「[ファイル構成](https://github.com/OyamaZemi/exercises2016/blob/master/ex01/README.md#ファイル構成)」にあるとおり，関数の定義は `.jl` ファイルにまとめ，そのデモを Jupyter notebook で行ってください．(EDIT: そしてそれらを GitHub にプッシュする．)

自分の notebook への，[nbviewer.jupyter.org](http://nbviewer.jupyter.org) 経由でのリンクを [ex01/notebooks.md](https://github.com/OyamaZemi/exercises2016/blob/master/ex01/notebooks.md) に加えてプルリクエスト投げてください．
1. (EDIT: GitHub にプッシュした) 自分の notebook の URL をコピーする
2. [nbviewer.jupyter.org](http://nbviewer.jupyter.org) を開いて URL をコピーして "Go!" を押す
3. 開いたページの URL をコピーしておく
4. このレポのフォークを作る (右上の "Fork" ボタンを押す)
5. [ex01/notebooks.md](https://github.com/OyamaZemi/exercises2016/blob/master/ex01/notebooks.md) を編集する
   
   ウェブブラウザで直接編集してもよいし，SourceTree でクローンを作りその中のファイルをテキストエディタで編集してもよい (`master` ブランチはいじらず，新しいブランチを作るようにすること)
   
   ファイルの終わりに次のような行を加える
   
   ```
   * [自分の名前](nbviewer.jupyter.org の URL)
   ```
   
   URL をペーストした結果は次のようになっているはず  
   
   ```
   * [自分の名前](http://nbviewer.jupyter.org/github/USER_NAME/REPO_NAME/blob/master/FILE_NAME.ipynb)
   ```
6. プルリクエストを投げる

わからないことがあったら，ここで質問してください．

**Comment by oyamad** [comment]
デモ・ノートブックでは，近似の残差 (residual) もプロットしてみましょう．

たとえば，近似する関数を

``` jl
f(x) = 2 .* cos(6x) .+ sin(14x) .+ 2.5
```

をとして，

``` jl
c_grid = 0:.2:1  # x のグリッド
Af = my_lin_interp(c_grid, f(c_grid))  # 自分で作った線形補間関数が生成する関数
residual(x) = f(x) - Af(x)  # 残差の関数
```

のようにして得られる関数 `residual` も (`f`, `Af` に加えて) プロットしてみましょう．

**Comment by ellenjunghyunkim** [comment]
自分の notebook への，nbviewer.jupyter.org 経由でのリンクを ex01/notebooks.md に加えてプルリクエスト投げる場合、４番に書いてある”このレポのフォークを作る (右上の "Fork" ボタンを押す)”のところがよくわからないです😥フォークを新しく作るってことですか？あるいはOyamazemiのところをフォークするということですか（しようと思ったがこれは許可されてないらしいです）？

**Comment by oyamad** [comment]
@ellenjunghyunkim さんはすでにフォークを作ってあるようです ( https://github.com/ellenjunghyunkim/exercises2016 )．

フォーク後にフォーク元は更新されているので，まずはそれをフォーク先に反映させる必要があります．
たとえば[ここ](http://qiita.com/takanemu/items/a576038f091c850693bc)を参考にしてやってみてください．

**Comment by oyamad** [comment]
「Type としての実装」は無理にやらなくてもよいので，[ベクトル化](https://github.com/OyamaZemi/exercises2016/tree/master/ex01#type-として実装)までできたら，`.jl` ファイルと notebook を分けて，[ex01/notebooks.md](https://github.com/OyamaZemi/exercises2016/blob/master/ex01/notebooks.md) にリンクを加えてプルリクエストしてください．そのあとで (ファイル名を変えずに) notebook を編集すれば，その変更は反映されます．

**Comment by Masaokb** [comment]
質問です、

Jupyter Notebook ViewerでURLを貼っても
400 : Bad Request
We couldn't render your notebook

Perhaps it is not valid JSON, or not the right URL.

If this should be a working notebook, please let us know.

The error was: Failed to connect to localhost port 8888: Connection refused
と出るんですがどうすればよいでしょう…

岡部

2016年5月21日 21:57 Daisuke Oyama notifications@github.com:

**Comment by oyamad** [comment]
貼ろうとした URL は何ですか．

**Comment by Masaokb** [comment]
あ、これGithubのurl使うんですね…

間違えてjupyter notebookのlocalのurl貼ってました、解決しました！

岡部

2016-05-22 13:41 GMT+09:00 Daisuke Oyama notifications@github.com:

**Comment by IoriS** [comment]
LoadError: syntax: missing comma or ) in argument list
while loading In[3], in expression starting on line 1

**Comment by IoriS** [comment]
println(readall(cat lin_interp.jl))

**Comment by oyamad** [comment]
Windows は

``` jl
println(readall(`cmd /c type lin_int.jl`))
```
