### ISSUE TITLE
Execise2

### ISSUE THREAD

**Issue by Masaokb** [OyamaZemi/exercises2016#16]
選考表の作り方からわからないんですが、
0~nまでの整数をランダムな順序で出力ってどうするんでしたっけ…

**Comment by myuuuuun** [comment]
``` julia
srand(1221)
ids = collect(1:10)
shuffle!( ids )

print(ids)
```

`srand(seed)` を指定すれば, 毎回同じ結果が得られます

**Comment by Masaokb** [comment]
おかげで（たぶん）中間課題出来ました(⌒▽⌒)

**Comment by oyamad** [comment]
[ここ](https://github.com/OyamaZemi/exercises2016/tree/master/ex02#ランダム選好リスト)に書いたとおり，ランダムに選好リストを生成する関数を書いたので必要があれば使ってみてください．
