### ISSUE TITLE
in-place transpose

### ISSUE THREAD

**Issue by myuuuuun** [OyamaZemi/exercises2016#26]
を実現する関数ってありましたか

like: 

```
a = [1 2; 3 4]
transpose!(a)
println(a)

>> [1 3
    2 4]
```

**Comment by oyamad** [comment]
具体的に何に使いたいのですか．

**Comment by myuuuuun** [comment]
pereferenceの行と列を入れ替えたい（`m_prefs[1, :]` で1番目の男の選好がとれるようにしたい）です

**Comment by myuuuuun** [comment]
新しく転置をした`new_m_prefs` を作るのはメモリの無駄&時間もかかるので, 元の行列のポインタを入れ替えるだけで転置を実現するような関数がないかと思いました

**Comment by oyamad** [comment]
「1番目の男の選好をとる」というのは新たに選好順序の1次元 Array を作りたいということですか．

**Comment by myuuuuun** [comment]
いえ, 仕様では

> m_prefs: (n+1) x mの2次元配列 
> 第 i 列 m_prefs[:, i] には男性 i が好きな女性の番号が順番に並べてある.

となっていますが, 私のDA関数の中ではm_prefsをm × (n+1) の行列として処理を書いている（そう書きたい）ので, m_prefsを転置したいが, 元の行列のコピーを作らずに転置をする方法は無いかということです

**Comment by oyamad** [comment]
たとえばこうするのがひとつの方法です．

``` jl
type RowMajorMatrix
    data::Matrix
end

Base.getindex(a::RowMajorMatrix, i::Int, j::Int) = a.data[j, i]
```

``` jl
julia> a = [1 2; 3 4]
2x2 Array{Int64,2}:
 1  2
 3  4

julia> a[1, 2]
2

julia> b = RowMajorMatrix(a)
RowMajorMatrix(2x2 Array{Int64,2}:
 1  2
 3  4)

julia> b[2, 1]
2
```

**Comment by myuuuuun** [comment]
やはり自分で書くしか無いですか
