### ISSUE TITLE
[test_deferred_acceptance.jl] module化するとtest側で関数が読み込めない

### ISSUE THREAD

**Issue by myuuuuun** [OyamaZemi/exercises2016#27]
と思うのですが, どうすればいいでしょうか. 

とりあえず

```
include(file_name)
const fn = GaleShapley.gale_shapley
```

とすることで対処しましたが……

**Comment by oyamad** [comment]
`test_deferred_acceptance.jl` の通りやるなら，7行目の `Main` を `GaleShapley` に変えたらどうなりますか．

わざわざ `function_name = "deferred_acceptance"` としているのは19行目で `$function_name` で string を呼びたいためだけで，ほんとは完全に不要です．

`include("file_name"); const fn = GaleShapley.gale_shapley` は正統だと思います．(`const fn = gale_shapley` では動きませんか？)

**Comment by myuuuuun** [comment]
```
const file_name = "gale_shapley.jl"
const function_name = "gale_shapley"

include(file_name)
const fn = getfield(GaleShapley, Symbol(function_name))
```

で動きました(`const fn = gale_shapley` はだめでした).   ありがとうございます
